2022-04-01 15:11:05,143 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:50]
2022-04-01 16:01:33,462 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:50]
2022-04-01 16:01:37,410 ERROR: Exception on /index [GET] [in /Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/seiscomp/webapp/dashboard/webapp/routes.py", line 27, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2022-04-19 11:51:36,400 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:50]
2022-04-19 13:42:13,719 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:50]
2022-04-19 13:43:45,990 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:50]
2022-04-19 13:47:24,579 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:50]
2022-04-19 13:47:37,750 ERROR: Exception on /dashboard/Bureau Maxime [GET] [in /Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/seiscomp/webapp/dashboard/webapp/routes.py", line 117, in server
    return render_template('server.html', server=server_x, posts=posts)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 31, in block 'content'
    <a href="{{ url_for('server') }}"> Update status </a></td>
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'server'. Did you forget to specify values ['server']?
2022-04-19 13:48:15,134 ERROR: Exception on /dashboard/Bureau Maxime [GET] [in /Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/seiscomp/webapp/dashboard/webapp/routes.py", line 117, in server
    return render_template('server.html', server=server_x, posts=posts)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 31, in block 'content'
    <a href="{{ url_for('server') }}"> Update status </a></td>
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'server'. Did you forget to specify values ['server']?
